name: python

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.py'
  workflow_dispatch:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Check formatting with Black
        run: black --check --diff app/
      
      - name: Sort imports with isort
        run: isort --check --diff --profile black app/
      
      - name: Lint with Flake8
        run: flake8 app/ --max-line-length=127
