name: Python Linting and Formatting

on:
  push:
    branches: [ main, master ]
    paths:
      - '**.py'
  pull_request:
    branches: [ main, master ]
    paths:
      - '**.py'
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Check formatting with Black
        run: black --check --diff app/
      
      - name: Lint with Flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 app/ --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 app/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      
      - name: Sort imports with isort
        run: isort --check --diff app/
      
      - name: Type check with mypy
        run: mypy --ignore-missing-imports app/
